os: linux
language: c

addons:
  apt:
    packages:
      - pandoc

install:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh > ./release.sh && chmod +x ./release.sh

script:
  - ./release.sh
  - ./release.sh -g classic
